application: cafe-map
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
    - url: /.*
      script: main.py
    - url: /remote_api
      script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
      login: admin
